---
version: '3'
services:
  app-test:
    image: wallarm/fast-example-rails
    environment:
      CAPYBARA_SERVER_HOST: app-test
    ports:
      - '3000:3000'
    networks:
      main:
        aliases:
          - app-test

  fast:
    image: wallarm/fast
    environment:
      WALLARM_API_TOKEN: ${WALLARM_API_TOKEN}
      CI_MODE: recording
    ports:
      - '8080:8080'
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    ports: ['4444:4444']
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

networks:
  main:
